/* songs-q2c.js quotes 111-125 */
window.SONGS_Q2 = window.SONGS_Q2 || {};
Object.assign(window.SONGS_Q2, {
"111":{"quoteEn":"If you are not part of the solution, you are part of the problem.","quoteHi":"यदि तुम समाधान का हिस्सा नहीं हो, तो तुम समस्या का हिस्सा हो।","quoteHe":"אם אינך מהווה חלק של הפתרון, אתה מהווה חלק של הבעיה."},
"112":{"quoteEn":"He who has learned to ride a horse will ride a horse.\nHe who has learned to deal with people will deal with people.","quoteHi":"जो घोड़े की सवारी करना सीख चुका है, वह घोड़े की सवारी करेगा।\nजो लोग लोगों से निपटना सीख चुके हैं, वह लोगों से निपटेगा।","quoteHe":"מי שלמד לרכוב על סוס – ירכב על סוס.\nמי שלמד להתמודד עם אנשים – יתמודד עם אנשים."},
"113":{"quoteEn":"The quarrel ends, but the words spoken never die.","quoteHi":"झगड़ा समाप्त हो जाता है, लेकिन कहे गए शब्द कभी नहीं मरते।","quoteHe":"הריב נפסק, אך המילים שנאמרו אינן מתות לעולם."},
"114":{"quoteEn":"The belly is wide and carries the world.","quoteHi":"पेट चौड़ा है और दुनिया को सहन करता है।","quoteHe":"הבטן רחבה וסוחבת את העולם."},
"115":{"quoteEn":"A lazy person works twice as hard.","quoteHi":"आलसी व्यक्ति दो गुना मेहनत करता है।","quoteHe":"עצלן עובד כפול."},
"116":{"quoteEn":"When you see a successful person, you only see their public glory, never the private sacrifices required to achieve it.","quoteHi":"जब आप किसी सफल व्यक्ति को देखते हैं, आप केवल उनकी सार्वजनिक महिमा देखते हैं, कभी भी उन निजी बलिदानों को नहीं देखते जो इसे हासिल करने के लिए आवश्यक थे।","quoteHe":"כשאתם רואים אדם מצליח, אתם רק רואים את התהילה הציבורית שלו, ואף פעם לא את ההקרבות הפרטיות שנדרשו כדי להגיע אליה.","cite":"Vaibhav Shah"},
"117":{"quoteEn":"You are what you repeatedly do. Excellence, then, is not an act, but a habit.","quoteHi":"आप वही हैं जो आप बार-बार करते हैं। उत्कृष्टता, इसलिए, एक क्रिया नहीं, बल्कि एक आदत है।","quoteHe":"אתם מה שאתם חוזרים ועושים כל הזמן. מצוינות אפוא, היא לא אקט, אלא הרגל.","cite":"Aristotle"},
"118":{"quoteEn":"When you see a successful person, you only see their public glory, never the private sacrifices required to achieve it.","quoteHi":"जब आप किसी सफल व्यक्ति को देखते हैं, आप केवल उनकी सार्वजनिक महिमा देखते हैं।","quoteHe":"כשאתם רואים אדם מצליח, אתם רק רואים את התהילה הציבורית שלו.","cite":"Vaibhav Shah"},
"119":{"quoteEn":"Try not to become a person of success, but rather a person of value.","quoteHi":"सफल व्यक्ति बनने की कोशिश मत करो, बल्कि मूल्यवान व्यक्ति बनने की कोशिश करो।","quoteHe":"נסו לא להפוך להיות אנשים מצליחים, אלא אנשים בעלי ערך.","cite":"Albert Einstein"},
"120":{"quoteEn":"Most of the stress people feel is not because they have too much to do, but because they haven’t finished what they started.","quoteHi":"लोगों को जो अधिकांश तनाव महसूस होता है, वह इसलिए नहीं कि उनके पास करने के लिए बहुत कुछ है, बल्कि इसलिए कि उन्होंने जो शुरू किया वह पूरा नहीं किया।","quoteHe":"רוב הלחץ שבני אדם מרגישים הוא לא כי יש להם יותר מדי מה לעשות, אלא כי הם לא סיימו את מה שהם התחילו.","cite":"David Allen"},
"121":{"quoteEn":"The distance between insanity and genius is measured only by success.","quoteHi":"पागलपन और प्रतिभा के बीच की दूरी केवल सफलता से मापी जाती है।","quoteHe":"המרחק בין חוסר שפיות וגאונות נמדד אך רק על ידי הצלחה.","cite":"Bruce Feirstein"},
"122":{"quoteEn":"Success is the sum of small efforts, repeated day in and day out.","quoteHi":"सफलता छोटे प्रयासों का योग है, जो रोज़ाना दोहराए जाते हैं।","quoteHe":"הצלחה היא סך של מאמצים קטנים, שחוזרים עליהם יום יום.","cite":"Robert Collier"},
"123":{"quoteEn":"The successful warrior is an average man with laser-like focus.","quoteHi":"सफल योद्धा एक औसत व्यक्ति है जिसके पास लेज़र जैसी एकाग्रता है।","quoteHe":"הלוחם המצליח הוא אדם ממוצע, עם יכולת ריכוז של לייזר.","cite":"Bruce Lee"},
"124":{"quoteEn":"The number one reason people fail in life is because they listen to their friends, family, and neighbors.","quoteHi":"लोग जीवन में असफल होते हैं इसका सबसे बड़ा कारण यह है कि वे अपने दोस्तों, परिवार और पड़ोसियों की सुनते हैं।","quoteHe":"הסיבה מספר 1 שאנשים נכשלים בחיים היא בגלל שהם מקשיבים לחברים שלהם, למשפחה ולשכנים.","cite":"Napoleon Hill"},
"125":{"quoteEn":"What would you attempt to do if you knew you could not fail?","quoteHi":"आप क्या करने का प्रयास करेंगे यदि आप जानते कि आप असफल नहीं होंगे?","quoteHe":"מה הייתם מנסים לעשות אם הייתם יודעים שלא תיכשלו?","cite":"Robert Schuller"}
});
window.GPC_SONGS_Q2 = window.SONGS_Q2;
