/* songs-all.js — the one file. */
window.SONGS_Q1=window.SONGS_Q1||{};
window.GPC_SONGS=window.GPC_SONGS||{};
window.SONGS=window.SONGS||{};
Object.assign(window.SONGS_Q1,{
"001":{"quoteEn":"Nature allows every person to cope with their fate.","quoteHi":"प्रकृति हर इंसान को अपने भाग्य का सामना करने की ताकत देती है।","quoteHe":"הטבע מאפשר לכל אדם להתמודד עם גורלו.","heVideo":"https://www.youtube.com/watch?v=zVi8AI9Yl6k","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"002":{"quoteEn":"The best way to take revenge on an enemy is not to become like him.","quoteHi":"दुश्मन से बदला लेने का सबसे अच्छा तरीका है उस जैसा न बनना।","quoteHe":"הדרך הטובה ביותר להתנקם באויב היא לא להידמות לו.","heVideo":"https://www.youtube.com/watch?v=hySvIlHhCgA","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"},
"003":{"quoteEn":"The consequences of anger are more serious than its causes.","quoteHi":"गुस्से के नतीजे उसके कारण से ज़्यादा ख़तरनाक होते हैं।","quoteHe":"תוצאות הכעס חמורות יותר מסיבותיו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=0D2yjGvcOCE","hiVideo":"https://www.youtube.com/watch?v=7W8IhwfEr0w"},
"004":{"quoteEn":"He who lives in peace with himself lives in peace with the whole world.","quoteHi":"जो इंसान अपने आप के साथ शांति में रहता है, वह पूरी दुनिया के साथ भी शांति में रहता है।","quoteHe":"מי שחי בשלום עם עצמו, חי בשלום עם כל העולם.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=sViXJypEWSk","hiVideo":"https://www.youtube.com/watch?v=1eHJ3I_Re3g"},
"005":{"quoteEn":"Death smiles at us all; all we can do is smile back.","quoteHi":"मौत हम सब पर मुस्कुराती है; हम बस उसे वापस मुस्कुरा सकते हैं।","quoteHe":"המוות מחייך לכולנו, והדבר היחיד שניתן לעשות הוא לחייך אליו בחזרה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=LKUVZe1wPOI","hiVideo":"https://www.youtube.com/watch?v=-W2dagktUp0"},
"006":{"quoteEn":"One of the unique qualities of a human being is to love even those who have failed.","quoteHi":"मनुष्य की एक विशेषता यह है कि वह उन लोगों से भी प्रेम कर सकता है जो असफल हो गए हैं।","quoteHe":"אחת התכונות המיוחדות של האדם היא לאהוב גם את אלו שנכשלו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=RerzmNafv1s","hiVideo":"https://www.youtube.com/watch?v=l7GR1S-HNGo"},
"007":{"quoteEn":"One of the unique qualities of a human being is to love even those who have failed.","quoteHi":"मनुष्य की एक विशेषता यह है कि वह उन लोगों से भी प्रेम कर सकता है जो असफल हो गए हैं।","quoteHe":"אחת התכונות המיוחדות של האדם היא לאהוב גם את אלו שנכשלו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=dfw60OCIiYs"},
"008":{"quoteEn":"A person’s worth is measured by the things he devotes himself to.","quoteHi":"मनुष्य का मूल्य उन चीज़ों से मापा जाता है जिनमें वह अपना समय और प्रयास लगाता है।","quoteHe":"ערכו של אדם נמדד לפי הדברים שבהם הוא עוסק.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=73qEBj-yOXA","hiVideo":"https://www.youtube.com/watch?v=9JDSGhhiOwI"},
"009":{"quoteEn":"Life is what our thoughts make it.","quoteHi":"जीवन वैसा ही होता है जैसा हमारी सोच उसे बना देती है।","quoteHe":"החיים הם מה שהמחשבות שלנו גורמות לנו להיות.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Ii8t-XIw6aM","hiVideo":"https://www.youtube.com/watch?v=nOAsaehfPrk"},
"010":{"quoteEn":"Do not waste time arguing about what a good man should be. Be one.","quoteHi":"यह मत बहस करो कि एक अच्छा इंसान क्या होता है। बस वैसा बनो।","quoteHe":"אל נא תתדיין בשאלה מהו אדם טוב, פשוט תהיה כזה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=TwHO5EwBg1U","hiVideo":"https://www.youtube.com/watch?v=lbfWsIpXsCA"},
"051":{"quoteEn":"Wise men speak because they have something to say; fools because they have to say something.","quoteHi":"बुद्धिमान इसलिए बोलते हैं कि उनके पास कहने को कुछ है; मूर्ख इसलिए कि उन्हें कुछ कहना ही है।","quoteHe":"חכמים מדברים כי יש להם מה לומר; כסילים מדברים כי הם מוכרחים לומר משהו.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=HXz70eAaiMA","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"071":{"quoteEn":"Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination.","quoteHi":"संगीत एक नैतिक नियम है।","quoteHe":"המוסיקה היא חוק מוסרי.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=6JNw4Qea2Yc","hiVideo":"https://www.youtube.com/watch?v=7OU_tOtkwqI"},
"091":{"quoteEn":"It is not because the well is too deep, but because the rope is too short.","quoteHi":"यह इसलिए नहीं कि कुआँ बहुत गहरा है, बल्कि इसलिए कि रस्सी बहुत छोटी है।","quoteHe":"אין זה משום שהבאר עמוקה מדי, אלא בגלל שהחבל קצר.","heVideo":"https://www.youtube.com/watch?v=63pxZIy7m_8","heLyrics":"https://lyricstranslate.com/en/eser-etzbaout-ten-fingers.html","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw","hiLyrics":"https://lyricstranslate.com/en/abhi-mujh-mein-kahin-still-somewhere-inside-me.html"}
});
(function(){var s=window.SONGS_Q1;Object.keys(s).forEach(function(k){var n=parseInt(k,10);if(isNaN(n))return;s[('000'+n).slice(-3)]=s[k];s[String(n)]=s[k];s[n]=s[k];window.GPC_SONGS[('000'+n).slice(-3)]=s[k];window.SONGS[('000'+n).slice(-3)]=s[k];});function p(){if(window.GPCPaintSongs)GPCPaintSongs();}p();setTimeout(p,400);setTimeout(p,1500);})();
