/* songs-q1f.js days 041-050 — loaded by songs-all.js */
window.SONGS_Q1 = window.SONGS_Q1 || {};
Object.assign(window.SONGS_Q1, {
"41":{"quoteEn":"Men and women are different in many ways, but they complement each other.","quoteHi":"पुरुष और महिलाएँ कई बातों में अलग हैं, पर वे एक दूसरे की पूरक करते हैं।","quoteHe":"גברים ונשים שונים בדרכים רבות, אך הם משלימים זה את זה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=C8wJ38CG3MI","hiVideo":"https://www.youtube.com/watch?v=7p7D_yqGHRY"},
"42":{"quoteEn":"Do not spoil what you have by desiring what you have not.","quoteHi":"जो पास नहीं है उसकी इच्छा में जो पास है उसे मत खोना।","quoteHe":"אל תקלקל את מה שיש לך על ידי חמדה למה שאין לך.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=I7_2x5el1_U","hiVideo":"https://www.youtube.com/watch?v=0WSlCZHZQ8E"},
"43":{"quoteEn":"The direction in which education starts a man will determine his future life.","quoteHi":"जिस दिशा में शिक्षा शुरू होती है, वही उसके भविष्य को निर्धारित करती है।","quoteHe":"הכיוון בו מתחילה החינוך של האדם הוא שיקבע את חייו העתידיים.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=-xA5YN-8Ql8","hiVideo":"https://www.youtube.com/watch?v=6Zqy2xwmY9s"},
"44":{"quoteEn":"Music gives a soul to the universe, wings to the mind, flight to the imagination and life to everything.","quoteHi":"संगीत ब्रह्मांड को आत्मा देती है, मन को पंख देती है, कल्पना को उडान देती है और सब कुछ जीवन देती है।","quoteHe":"המוסיקה נותנת נשמה ליקום, כנפיים לתודעה, מעוף לדמיון וחיים לכל דבר.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=6JNw4Qea2Yc","hiVideo":"https://www.youtube.com/watch?v=7OU_tOtkwqI"},
"45":{"quoteEn":"Be kind, for everyone you meet is fighting a harder battle.","quoteHi":"दयाळु बनो, क्योंकि जिससे भी तुम मिलते हो वह किसी बड़ी लड़ाई लड़ रहा है।","quoteHe":"היה טוב, כי כל אדם שאתה פוגש נלחם בקרב קשה יותר.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=9-CStyRTbe4","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"},
"46":{"quoteEn":"The beginning is the most important part of the work.","quoteHi":"शुरुआत ही काम का सबसे महत्वपूर्ण भाग है।","quoteHe":"ההתחלה היא החלק החשוב ביותר בעבודה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=zVi8AI9Yl6k","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"47":{"quoteEn":"Those who are able to see beyond the shadows and lies of their culture will never be understood, let alone believed, by the masses.","quoteHi":"जो अपनी संस्कृति के सायों और झूठों से परे देख सकते हैं, उन्हें जनसाधारण न समझेगा, मानने की तो बात ही क्या।","quoteHe":"מי שמסוגל לראות מעבר לצללים ולשקרי התרבות שלו, לא יובן על ידי ההמון – קל וחומר שיאמינו לו.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=63pxZIy7m_8","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"48":{"quoteEn":"For a man to conquer himself is the first and noblest of all victories.","quoteHi":"अपने आप पर जीत पाना सबसे पहली और सबसे उत्तम विजय है।","quoteHe":"לכבוש את עצמך – זו הניצחון הראשון והנאצל מכל.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=HHo9Vwi3iPo","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"49":{"quoteEn":"Good people do not need laws to tell them to act responsibly, while bad people will find a way around the laws.","quoteHi":"भले लोगों को जिम्मेदार बताने के लिए कानून की ज़रूरत नहीं, बुरे लोग कानून का चक्कर निकाल निकाल लेते हैं।","quoteHe":"אנשים טובים לא זקוקים לחוקים שיאמרו להם כיצד לנהוג, ואנשים רעים ימצאו דרך לעקוף סביבם.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=ITzMQKr523Y","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"50":{"quoteEn":"The measure of a man is what he does with power.","quoteHi":"इन्सान की परख यह है कि वह शक्ति के साथ क्या करता है।","quoteHe":"מידת האדם היא מה שהוא עושה עם הכוח.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=qfxgip3SYlA","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"}
});
window.GPC_SONGS_Q1 = window.SONGS_Q1;
