/* songs-q1g.js 051-070 loaded by songs-all.js */
window.SONGS_Q1=window.SONGS_Q1||{};
Object.assign(window.SONGS_Q1,{
"51":{"quoteEn":"Wise men speak because they have something to say; fools because they have to say something.","quoteHi":"बुद्धिमान इसलिए बोलते हैं कि उनके पास कहने को कुछ है; मूर्ख इसलिए कि उन्हें कुछ कहना ही है।","quoteHe":"חכמים מדברים כי יש להם מה לומר; כסילים מדברים כי הם מוכרחים לומר משהו.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=HXz70eAaiMA","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"52":{"quoteEn":"Necessity is the mother of invention.","quoteHi":"आवश्यकता आविष्कार की जननी है।","quoteHe":"ההכרח היא אם ההמצאה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=kJnOQQ815LQ","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"53":{"quoteEn":"Courage is knowing what not to fear.","quoteHi":"साहस यह जानना है कि किस चीज़ से नहीं डरना।","quoteHe":"אומץ הוא לדעת ממה לא לפחוד.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=E9jRgSVkOF0","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"54":{"quoteEn":"The first and greatest victory is to conquer yourself.","quoteHi":"पहली और सबसे बड़ी जीत अपने आप पर विजय पाना है।","quoteHe":"הניצחון הראשון והגדול ביותר הוא לכבוש את עצמך.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=LWFEEsU-Y6M","hiVideo":"https://www.youtube.com/watch?v=vEe-UgJvUHE"},
"55":{"quoteEn":"Wealth is the parent of luxury and indolence, and poverty of meanness and viciousness.","quoteHi":"धन अयाश और आलस्य का जनक है, और गरीबी नीचता और दुर्व्यव्यवहार की।","quoteHe":"העושר הוא אב המותרות והעצלות, והעוני אב הנמיכות והרשע.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=NpAhYc_5-fs","hiVideo":"https://www.youtube.com/watch?v=_RFUvHlW41A"},
"56":{"quoteEn":"At the touch of love everyone becomes a poet.","quoteHi":"प्रेम के स्पर्श से हर कोई कवि बन जाता है।","quoteHe":"במגע האהבה כל אדם הופך למשורר.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=cLPFb305l44","hiVideo":"https://www.youtube.com/watch?v=cYOB941gyXI"},
"57":{"quoteEn":"A good decision is based on knowledge and not on numbers.","quoteHi":"अच्छा निर्णय ज्ञान पर टिकता है, संख्याओं पर नहीं।","quoteHe":"החלטה טובה מבוססת על ידע, לא על מספרים.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=VT1R37o-d3I","hiVideo":"https://www.youtube.com/watch?v=Umqb9KENgmk"},
"58":{"quoteEn":"He who is not a good servant will not be a good master.","quoteHi":"जो अच्छा सेवक नहीं, वह अच्छा स्वामी भी नहीं बनेगा।","quoteHe":"מי שאינו משרת טוב לא יהיה אדון טוב.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=u95eSORTRDs","hiVideo":"https://www.youtube.com/watch?v=UNs50T6EYwE"},
"59":{"quoteEn":"The greatest wealth is to live content with little.","quoteHi":"सबसे बड़ा धन थोड़े में संतुष्ट रहना है।","quoteHe":"העושר הגדול ביותר הוא לחיות שבע רצון במעט.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=Hl0VJo0LZao","hiVideo":"https://www.youtube.com/watch?v=7W8IhwfEr0w"},
"60":{"quoteEn":"Ignorance, the root and stem of all evil.","quoteHi":"अज्ञान ही सब बुराई की जड़ और तना है।","quoteHe":"הבערות היא שורש וגזע של כל רע.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=ty0Q9g7gClU","hiVideo":"https://www.youtube.com/watch?v=-W2dagktUp0"},
"61":{"quoteEn":"Justice in the State is possible only when it first resides in the hearts of the citizens.","quoteHi":"राज्य में न्याय तभी संभव है जब वह पहले नागरिकों के हृदय में हो।","quoteHe":"צדק במדינה אפשרי רק כשהוא שרוי תחילה בלב האזרחים.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=oLAOEVYDcps","hiVideo":"https://www.youtube.com/watch?v=1eHJ3I_Re3g"},
"62":{"quoteEn":"There are two things a person should never be angry at: what they can help, and what they cannot.","quoteHi":"दो बातों पर कभी गुस्सा नहीं करना चाहिए: जिसे बदला जा सके, और जिसे नहीं बदल सकते।","quoteHe":"שני דברים שלעולם אל לכעוס עליהם: מה שביכלתך לשנות, ומה שאי אפשר לשנות.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=w56GvpfcP6c","hiVideo":"https://www.youtube.com/watch?v=7p7D_yqGHRY"},
"64":{"quoteEn":"Thinking: the talking of the soul with itself.","quoteHi":"सोचना आत्मा की अपने साथ बातचीत है।","quoteHe":"חשיבה: שיחת הנפש עם עצמה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=nbW_Hf-wfrc","hiVideo":"https://www.youtube.com/watch?v=0WSlCZHZQ8E"},
"65":{"quoteEn":"Knowledge which is acquired under compulsion obtains no hold on the mind.","quoteHi":"जो ज्ञान मजबूरी से आता है, वह मन में टिकता नहीं।","quoteHe":"ידע שנרכש בכפייה אינו אוחז בנפש.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=QtfyyuZrUqY","hiVideo":"https://www.youtube.com/watch?v=6Zqy2xwmY9s"},
"66":{"quoteEn":"No one is more hated than he who speaks the truth.","quoteHi":"सच्च बोलने वाले से ज्यादा कोई नहीं होता।","quoteHe":"אין שנאוי יותר ממי שאומר את האמת.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=VfD7WNKNrAQ","hiVideo":"https://www.youtube.com/watch?v=7OU_tOtkwqI"},
"67":{"quoteEn":"Death is not the worst that can happen to men.","quoteHi":"मौत मनुष्य के साथ होने वाली सबसे बुरी बात नहीं है।","quoteHe":"המוות אינו הדבר הרע ביותר שיכול לקרות לאדם.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=RMwhKx8_X8A","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"},
"68":{"quoteEn":"We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.","quoteHi":"अँधेरे से डरने बच्चे को माफ कर सकते हैं; असली त्रासदी तब है जब इन्सान प्रकाश से डरे।","quoteHe":"קל לסלוח לילד שמפחד מהחשכה; הטרגדיה האמיתית היא כשאנשים מפחדים מהאור.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=MQuaIYRDO6s","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"69":{"quoteEn":"The wisest have the most authority.","quoteHi":"सबसे बुद्धिमान के पास सबसे अधिक अधिकार होता है।","quoteHe":"לחכמים ביותר יש הסמכות הרבה ביותר.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=fZ26yiGviZA","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"70":{"quoteEn":"Honesty is for the most part less profitable than dishonesty.","quoteHi":"ईमानदारी अक्सर बेईमानी से कम फायदेमंद रहती है।","quoteHe":"הכנות לפי רוב רווחית פחות מהיושר הישר.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=CMW0zhhV0yI","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"}
});
window.GPC_SONGS_Q1=window.SONGS_Q1;
