/* songs-q1c.js days 002-015 */
window.SONGS_Q1 = window.SONGS_Q1 || {};
window.SONGS_Q1B = window.SONGS_Q1B || {};
(function(){
var d={
"2":{"quoteEn":"The best way to take revenge on an enemy is not to become like him.","quoteHi":"दुश्मन से बदला लेने का सबसे अच्छा तरीका है उस जैसा न बनना।","quoteHe":"הדרך הטובה ביותר להתנקם באויב היא לא להידמות לו.","heVideo":"https://www.youtube.com/watch?v=hySvIlHhCgA","heLyrics":"https://lyricstranslate.com/en/%D7%90%D7%99%D7%9F-%D7%99%D7%95%D7%AA%D7%A8-%D7%9E%D7%95%D7%A2%D7%93%D7%95%D7%A0%D7%99%D7%9D-ein-yoter-moadonim-no-more-clubbing.html","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4","hiLyrics":"https://lyricstranslate.com/en/pal-pal-dil-ke-paas-every-moment-heart.html"},
"3":{"quoteEn":"The consequences of anger are more serious than its causes.","quoteHi":"गुस्से के नतीजे उसके कारण से ज़्यादा ख़तरनाक होते हैं।","quoteHe":"תוצאות הכעס חמורות יותר מסיבותיו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=0D2yjGvcOCE","heLyrics":"https://lyricstranslate.com/en/do-you-love-me-do-you-love-me.html-0","hiVideo":"https://www.youtube.com/watch?v=7W8IhwfEr0w","hiLyrics":"https://lyricstranslate.com/en/kisi-ka-bhai-kisi-ki-tere-bina-english"},
"4":{"quoteEn":"He who lives in peace with himself lives in peace with the whole world.","quoteHi":"जो इंसान अपने आप के साथ शांति में रहता है, वह पूरी दुनिया के साथ भी शांति में रहता है।","quoteHe":"מי שחי בשלום עם עצמו, חי בשלום עם כל העולם.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=sViXJypEWSk","heLyrics":"https://lyricstranslate.com/en/eretz-ahuva-beloved-land.html","hiVideo":"https://www.youtube.com/watch?v=1eHJ3I_Re3g","hiLyrics":"https://lyricstranslate.com/en/chura-liya-hai-tumne-jo-dil-ko-now-you-have-stolen-my-heart.html"},
"5":{"quoteEn":"Death smiles at us all; all we can do is smile back.","quoteHi":"मौत हम सब पर मुस्कुराती है; हम बस उसे वापस मुस्कुरा सकते हैं।","quoteHe":"המוות מחייך לכולנו, והדבר היחיד שניתן לעשות הוא לחייך אליו בחזרה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=LKUVZe1wPOI","heLyrics":"https://lyricstranslate.com/en/hazi-meshuga-half-madman.html","hiVideo":"https://www.youtube.com/watch?v=-W2dagktUp0","hiLyrics":"https://lyricstranslate.com/en/kbhii-kbhii-mere-dil-men-khhyaal-aataa-hai-kabhi.html"},
"6":{"quoteEn":"One of the unique qualities of a human being is to love even those who have failed.","quoteHi":"मनुष्य की एक विशेषता यह है कि वह उन लोगों से भी प्रेम कर सकता है जो असफल हो गए हैं।","quoteHe":"אחת התכונות המיוחדות של האדם היא לאהוב גם את אלו שנכשלו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=RerzmNafv1s","heLyrics":"https://lyricstranslate.com/en/asur-forbidden.html","hiVideo":"https://www.youtube.com/watch?v=l7GR1S-HNGo"},
"7":{"quoteEn":"One of the unique qualities of a human being is to love even those who have failed.","quoteHi":"मनुष्य की एक विशेषता यह है कि वह उन लोगों से भी प्रेम कर सकता है जो असफल हो गए हैं।","quoteHe":"אחת התכונות המיוחדות של האדם היא לאהוב גם את אלו שנכשלו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=dfw60OCIiYs","heLyrics":"https://lyricstranslate.com/en/af-paam-lo-levad-never-alone.html","hiVideo":"https://open.spotify.com/track/6RELGnjAoxtO1IRYUcEcta","hiLyrics":"https://lyricstranslate.com/en/mukesh-ek-pyar-ka-nagma-hai-lyrics.html"},
"8":{"quoteEn":"A person’s worth is measured by the things he devotes himself to.","quoteHi":"मनुष्य का मूल्य उन चीज़ों से मापा जाता है जिनमें वह अपना समय और प्रयास लगाता है।","quoteHe":"ערכו של אדם נמדד לפי הדברים שבהם הוא עוסק.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=73qEBj-yOXA","heLyrics":"https://lyricstranslate.com/en/mexico-mexico.html","hiVideo":"https://www.youtube.com/watch?v=9JDSGhhiOwI","hiLyrics":"https://lyricstranslate.com/en/r-rahman-tere-bina-lyrics"},
"9":{"quoteEn":"Life is what our thoughts make it.","quoteHi":"जीवन वैसा ही होता है जैसा हमारी सोच उसे बना देती है।","quoteHe":"החיים הם מה שהמחשבות שלנו גורמות לנו להיות.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Ii8t-XIw6aM","heLyrics":"https://lyricstranslate.com/en/etach-you.html","hiVideo":"https://www.youtube.com/watch?v=nOAsaehfPrk","hiLyrics":"https://lyricstranslate.com/en/jaan-pehechaan-ho-may-there-be-familiarity.html"},
"10":{"quoteEn":"Do not waste time arguing about what a good man should be. Be one.","quoteHi":"यह मत बहस करो कि एक अच्छा इंसान क्या होता है। बस वैसा बनो।","quoteHe":"אל נא תתדיין בשאלה מהו אדם טוב, פשוט תהיה כזה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=TwHO5EwBg1U","heLyrics":"https://lyricstranslate.com/en/aba-dad.html","hiVideo":"https://www.youtube.com/watch?v=lbfWsIpXsCA","hiLyrics":"https://lyricstranslate.com/en/ye-shaam-mastani-lively-evening.html"},
"11":{"quoteEn":"When you arise in the morning, think of what a privilege it is to be alive—to breathe, to think, to enjoy, to love.","quoteHi":"जब तुम सुबह जागो, तो सोचो कि जीवित होना कितना बड़ा सौभाग्य है—सांस लेना, सोचना, आनंद लेना और प्रेम करना।","quoteHe":"כשתתעורר בבוקר, חשוב על הזכות שנפלה בחלקך לחיות, ליהנות, לחשוב ולאהוב.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=EI2joAy8D18","hiVideo":"https://www.youtube.com/watch?v=g0eO74UmRBs","hiLyrics":"https://lyricstranslate.com/en/kal-ho-naa-ho-story-may-not-be-there-tomorrow.html"},
"12":{"quoteEn":"Do every act of your life as if it were your last.","quoteHi":"अपने जीवन का हर काम ऐसे करो जैसे वह तुम्हारा आख़िरी काम हो।","quoteHe":"עשה כל דבר בחייך כאילו הוא הדבר האחרון שתעשה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=RerzmNafv1s","heLyrics":"https://lyricstranslate.com/en/bishvilcha-your-sake.html","hiVideo":"https://www.youtube.com/watch?v=qoq8B8ThgEM","hiLyrics":"https://lyricstranslate.com/en/tujh-mein-rab-dikhta-hai-i-see-my-god-you.html"},
"13":{"quoteEn":"Just because something seems difficult, do not think it is impossible.","quoteHi":"सिर्फ इसलिए कि कोई चीज़ तुम्हें कठिन लगती है, यह मत सोचो कि वह असंभव है।","quoteHe":"רק מפני שמשהו נראה לך קשה, אל תחשוב שהוא בלתי אפשרי.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=lgkKvOEo8q4","heLyrics":"https://lyricstranslate.com/en/kol-ha-zman-omeret-you-say-all-time.html","hiVideo":"https://www.youtube.com/watch?v=ovR_7R9I_vI","hiLyrics":"https://lyricstranslate.com/en/mohit-chauhan-pee-loon-english"},
"14":{"quoteEn":"The best way to predict the future is to create it!","quoteHi":"भविष्य की भविष्यवाणी करने का सबसे अच्छा तरीका है उसे खुद बनाना।","quoteHe":"הדרך הטובה ביותר לחזות את העתיד היא ליצור אותו!","cite":"Peter Drucker","heVideo":"https://www.youtube.com/watch?v=lLmXR0x6ckA","heLyrics":"https://lyricstranslate.com/en/ima-shelcha-your-mother.html","hiVideo":"https://open.spotify.com/track/5itw0WzsobhLXyxUuAj8OQ","hiLyrics":"https://lyricstranslate.com/en/lata-mangeshkar-dil-paagal-hai-english"},
"15":{"quoteEn":"Despite a broken heart, people keep going.","quoteHi":"टूटे हुए दिल के बावजूद, लोग आगे बढ़ते रहते हैं।","quoteHe":"למרות הלב השבור, אנשים ממשיכים הלאה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=5kz28Hh9VVk","heLyrics":"https://lyricstranslate.com/en/what-those.html","hiVideo":"https://www.youtube.com/watch?v=xRb8hxwN5zc","hiLyrics":"https://lyricstranslate.com/en/agar-tum-saath-ho-if-you-are-me.html"}
};
Object.assign(window.SONGS_Q1, d);
Object.assign(window.SONGS_Q1B, d);
window.GPC_SONGS_Q1 = window.SONGS_Q1;
})();
