/* fold into songs-q1.js */
Object.assign(window.SONGS_Q1=window.SONGS_Q1||{}, {
"21":{"quoteEn":"At any hour you choose, it is within your power to withdraw into yourself.","quoteHi":"जब भी तुम चाहो, तुम्हारे हाथ में है कि तुम एकांत में जा सको।","quoteHe":"כל שעה שתחפוץ, בידך להתבודד.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=cLPFb305l44","hiVideo":"https://www.youtube.com/watch?v=cYOB941gyXI"},
"22":{"quoteEn":"We are all fleeting—the one who remembers and the one who is remembered.","quoteHi":"हम सब नश्वर हैं—याद करने वाला भी और जिसे याद किया जाता है वह भी।","quoteHe":"כולנו בני חלוף – הזוכר, ומושא זכרונו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=VT1R37o-d3I","hiVideo":"https://www.youtube.com/watch?v=M1mVWZKFcUw"},
"23":{"quoteEn":"Nowhere can a person find a more peaceful refuge than in his own soul.","quoteHi":"कहीं भी मनुष्य को अपनी आत्मा से अधिक शांत आश्रय नहीं मिल सकता।","quoteHe":"בשום מקום לא יוכל האדם למצוא מקלט שליו יותר מאשר בנפשו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=u95eSORTRDs","hiVideo":"https://www.youtube.com/watch?v=Umqb9KENgmk"},
"24":{"quoteEn":"Whenever trouble comes to you, remember: to bear it with nobility is the wealth of the soul.","quoteHi":"जब भी तुम्हारे उपर कोई मुसीबत आए, याद रखो—उसे गरिमा के साथ सहना ही आत्मा की संपत्ति है।","quoteHe":"בכל צרה שתבוא עליך זכור; לשאת אותה באצילות, הוא עושרה של הנפש.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Hl0VJo0LZao","hiVideo":"https://www.youtube.com/watch?v=UNs50T6EYwE"},
"25":{"quoteEn":"If you find a good wife, you will be happy; if not, you will become a philosopher.","quoteHi":"अगर तुम्हें अच्छी पत्नी मिल जाए तो तुम खुश रहोगे; अगर नहीं, तो तुम दार्शनिक बन जाओगे।","quoteHe":"אם אתה מוצא אישה טובה אתה תהיה מאושר, אם לא, אתה תהיה פילוסוף.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=ty0Q9g7gClU","hiVideo":"https://open.spotify.com/track/3t3wsY5IdLVzB9WidegJSU"},
"26":{"quoteEn":"Do not let grass grow on the path of friendship.","quoteHi":"दोस्ती के रास्ते पर घास मत उगने दो।","quoteHe":"אל תתנו לדשא לצמוח על נתיב הידידות.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=oLAOEVYDcps","hiVideo":"https://open.spotify.com/track/5YyXp1D6QxK2yZtXOtOid5"},
"27":{"quoteEn":"Kings or rulers are not those who hold the scepter, but those who know how to command.","quoteHi":"राजा या शासक वे नहीं होते जिनके पास राजदंड होता है, बल्कि वे होते हैं जो आदेश देना जानते हैं।","quoteHe":"מלכים או שליטים אינם אלה שיש להם שרביט, אלא אלה שיודעים איך לפקד.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=w56GvpfcP6c","hiVideo":"https://open.spotify.com/track/4brSaQIT3bnnE41D042fgL"},
"28":{"quoteEn":"No one is happy throughout their entire life.","quoteHi":"कोई भी अपने पूरे जीवन में हमेशा खुश नहीं रहता।","quoteHe":"אף אחד לא מאושר לאורך כל חייהם.","cite":"Euripides","heVideo":"https://www.youtube.com/watch?v=nbW_Hf-wfrc","hiVideo":"https://open.spotify.com/track/6eO9LvEiMqh1CAsa6y3wXP"},
"29":{"quoteEn":"Human science consists more in the destruction of errors than in the discovery of truth.","quoteHi":"मानव ज्ञान सत्य की खोज से अधिक गलतियों को नष्ट करने में लगा होता है।","quoteHe":"המדע האנושי מורכב יותר בהרס שגיאות מאשר גילוי האמת.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=QtfyyuZrUqY","hiVideo":"https://open.spotify.com/track/0Bz7dfqPY4JOGZO3O1j8Wh"},
"30":{"quoteEn":"Hunger is the best sauce.","quoteHi":"सबसे अच्छा स्वाद भूख देती है।","quoteHe":"הרוטב הטוב ביותר הוא רעב.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=VfD7WNKNrAQ","hiVideo":"https://open.spotify.com/track/3TAhWtQnpoL5Vl9VQPl9fU"}
});
