/* songs-q1h.js 071-091 */
window.SONGS_Q1=window.SONGS_Q1||{};
Object.assign(window.SONGS_Q1,{
"71":{"quoteEn":"Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination.","quoteHi":"संगीत एक नैतिक नियम है। यह ब्रह्मांड को आत्मा देती है, मन को पंख देती है।","quoteHe":"המוסיקה היא חוק מוסרי. היא נותנת נשמה ליקום וכנפיים לתודעה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=6JNw4Qea2Yc","hiVideo":"https://www.youtube.com/watch?v=7OU_tOtkwqI"},
"72":{"quoteEn":"The price good men pay for indifference to public affairs is to be ruled by evil men.","quoteHi":"भले लोगों को लोककार्य से बेखबर रहने की कीमत यह है कि बुरे लोग उनपर राज चलाएँगे।","quoteHe":"המחיר שאנשים טובים משלמים על אדישות לענייני הציבור הוא שרשעים ימלכו בהם.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=C8wJ38CG3MI","hiVideo":"https://www.youtube.com/watch?v=7p7D_yqGHRY"},
"73":{"quoteEn":"Opinion is the medium between knowledge and ignorance.","quoteHi":"राय ज्ञान और अज्ञान के बीच की कजी है।","quoteHe":"הדעה היא האמצע בין ידע לבערות.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=I7_2x5el1_U","hiVideo":"https://www.youtube.com/watch?v=0WSlCZHZQ8E"},
"74":{"quoteEn":"The soul takes flight to the world that is invisible.","quoteHi":"आत्मा उस संसार की ओर उडान भरती है जो दिखाई नहीं देता।","quoteHe":"הנפש ממריאה אל העולם שאינו נראה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=-xA5YN-8Ql8","hiVideo":"https://www.youtube.com/watch?v=6Zqy2xwmY9s"},
"75":{"quoteEn":"Better a little which is well done, than a great deal imperfectly.","quoteHi":"थोड़ा अच्छा काम बहुत सा काम बुरा, जो अधूरा हो।","quoteHe":"מעט שנעשה היטב עדיף על הרבה שנעשה בחיסור.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=9-CStyRTbe4","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"},
"76":{"quoteEn":"Excess of liberty passes into excess of slavery.","quoteHi":"अत्यधिक स्वतंत्रता अत्यधिक गुलामी में बदल जाती है।","quoteHe":"הפרזת חופש עוברת להפרזת עבדות.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=HHo9Vwi3iPo","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"77":{"quoteEn":"There is no harm in repeating a good thing.","quoteHi":"अच्छी बात को दोहराना हानिकार नहीं है।","quoteHe":"אין רע בלחזור על דבר טוב.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=ITzMQKr523Y","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"78":{"quoteEn":"People can either nourish you and help you grow, or stunt your growth.","quoteHi":"लोग या तुम्हें पलन देकर बढ़ाते हैं, या तुम्हारी बढ़त रोक देते हैं।","quoteHe":"אנשים יכולים לזין אותך או לעצור את צמיחתך.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=qfxgip3SYlA","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"79":{"quoteEn":"He was a wise man who invented beer.","quoteHi":"बीयर बनाने वाला बुद्धिमान था।","quoteHe":"חכם היה האיש שהמציא את הבירה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=nbW_Hf-wfrc","hiVideo":"https://www.youtube.com/watch?v=7W8IhwfEr0w"},
"80":{"quoteEn":"The most virtuous are those who content themselves with being virtuous without seeking to appear so.","quoteHi":"सबसे नेकी वे हैं जो नेक होना चाहते हैं, नेक दिखना नहीं।","quoteHe":"המעלים ביותר הם אלה שמסתפקים בהיות מעלים בלי לבקש להיראות כאלה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=ty0Q9g7gClU","hiVideo":"https://www.youtube.com/watch?v=-W2dagktUp0"},
"81":{"quoteEn":"Astronomy compels the soul to look upwards.","quoteHi":"खगोल विज्ञान आत्मा को ऊपर देखने को मजबूर करता है।","quoteHe":"האסטרונומיה מכריחה את הנפש להביט כלפי מעלה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=oLAOEVYDcps","hiVideo":"https://www.youtube.com/watch?v=1eHJ3I_Re3g"},
"82":{"quoteEn":"The good is the beautiful.","quoteHi":"भला ही सुन्दर है।","quoteHe":"הטוב הוא היפה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=w56GvpfcP6c","hiVideo":"https://www.youtube.com/watch?v=7p7D_yqGHRY"},
"83":{"quoteEn":"When the mind is thinking, it is talking to itself.","quoteHi":"जब मन सोचता है, वह अपने से बात कर रहा होता है।","quoteHe":"כשהתודעה חושבת, היא מדברת עם עצמה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=QtfyyuZrUqY","hiVideo":"https://www.youtube.com/watch?v=6Zqy2xwmY9s"},
"84":{"quoteEn":"Man is a being in search of meaning.","quoteHi":"मनुष्य अर्थ की खोज में लगा हुआ प्राणी है।","quoteHe":"האדם הוא יצור המחפש משמעות.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=VfD7WNKNrAQ","hiVideo":"https://www.youtube.com/watch?v=7OU_tOtkwqI"},
"85":{"quoteEn":"The beginning is the most important part of the work.","quoteHi":"शुरुआत ही काम का सबसे महत्वपूर्ण भाग है।","quoteHe":"ההתחלה היא החלק החשוב ביותר בעבודה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=63pxZIy7m_8","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"86":{"quoteEn":"Apply yourself both now and in the next life. Without effort, you cannot be prosperous. Though the land be good, you cannot have an abundant crop without cultivation.","quoteHi":"अभी और अगले जन्म दोनों मेहनत लगाओ। बिना मेहनत समृद्धि नहीं मिलती।","quoteHe":"השתדל עכשיו ובחיים הבאים. בלי מאמץ אי אפשר לשגשג.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=RMwhKx8_X8A","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"},
"87":{"quoteEn":"Love is a serious mental disease.","quoteHi":"प्रेम एक गंभीर मानसिक रोग है।","quoteHe":"האהבה היא מחלה נפשית קשה.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=cLPFb305l44","hiVideo":"https://www.youtube.com/watch?v=cYOB941gyXI"},
"88":{"quoteEn":"The greatest mistake is to be continually fearing you will make one.","quoteHi":"सबसे बड़ी भूल यह है कि सदा डरे कि कोई भूल हो जाएगी।","quoteHe":"הטעות הגדולה ביותר היא לפחוד תמיד שתטעה.","heVideo":"https://www.youtube.com/watch?v=MQuaIYRDO6s","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"89":{"quoteEn":"Nothing beautiful without struggle.","quoteHi":"बिना संघर्ष कुछ सुन्दर नहीं।","quoteHe":"אין יפה בלי מאבק.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=fZ26yiGviZA","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"90":{"quoteEn":"The unexamined life is not worth living.","quoteHi":"बिना जाँचे जीवन जीने योग्य नहीं।","quoteHe":"חיים שלא נבחנו אינם שווים לחיות.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=E9jRgSVkOF0","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"},
"91":{"quoteEn":"It is not because the well is too deep, but because the rope is too short.","quoteHi":"यह इसलिए नहीं कि कुआँ बहुत गहरा है, बल्कि इसलिए कि रस्सी बहुत छोटी है।","quoteHe":"אין זה משום שהבאר עמוקה מדי, אלא בגלל שהחבל קצר.","heVideo":"https://www.youtube.com/watch?v=63pxZIy7m_8","heLyrics":"https://lyricstranslate.com/en/eser-etzbaout-ten-fingers.html","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw","hiLyrics":"https://lyricstranslate.com/en/abhi-mujh-mein-kahin-still-somewhere-inside-me.html"}
});
window.GPC_SONGS_Q1=window.SONGS_Q1;
