/* songs-q1b.js Q1 remainder — live blog already loads this */
window.SONGS_Q1 = window.SONGS_Q1 || {};
Object.assign(window.SONGS_Q1, {
"2":{"quoteEn":"The best way to take revenge on an enemy is not to become like him.","quoteHi":"दुश्मन से बदला लेने का सबसे अच्छा तरीका है उस जैसा न बनना।","quoteHe":"הדרך הטובה ביותר להתנקם באויב היא לא להידמות לו.","heVideo":"https://www.youtube.com/watch?v=hySvIlHhCgA","heLyrics":"https://lyricstranslate.com/en/%D7%90%D7%99%D7%9F-%D7%99%D7%95%D7%AA%D7%A8-%D7%9E%D7%95%D7%A2%D7%93%D7%95%D7%A0%D7%99%D7%9D-ein-yoter-moadonim-no-more-clubbing.html","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4","hiLyrics":"https://lyricstranslate.com/en/pal-pal-dil-ke-paas-every-moment-heart.html"},
"3":{"quoteEn":"The consequences of anger are more serious than its causes.","quoteHi":"गुस्से के नतीजे उसके कारण से ज़्यादा ख़तरनाक होते हैं।","quoteHe":"תוצאות הכעס חמורות יותר מסיבותיו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=0D2yjGvcOCE","heLyrics":"https://lyricstranslate.com/en/do-you-love-me-do-you-love-me.html-0","hiVideo":"https://www.youtube.com/watch?v=7W8IhwfEr0w","hiLyrics":"https://lyricstranslate.com/en/kisi-ka-bhai-kisi-ki-tere-bina-english"},
"4":{"quoteEn":"He who lives in peace with himself lives in peace with the whole world.","quoteHi":"जो इंसान अपने आप के साथ शांति में रहता है, वह पूरी दुनिया के साथ भी शांति में रहता है।","quoteHe":"מי שחי בשלום עם עצמו, חי בשלום עם כל העולם.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=sViXJypEWSk","hiVideo":"https://www.youtube.com/watch?v=1eHJ3I_Re3g","hiLyrics":"https://lyricstranslate.com/en/chura-liya-hai-tumne-jo-dil-ko-now-you-have-stolen-my-heart.html"},
"5":{"quoteEn":"Death smiles at us all; all we can do is smile back.","quoteHi":"मौत हम सब पर मुस्कुराती है; हम बस उसे वापस मुस्कुरा सकते हैं।","quoteHe":"המוות מחייך לכולנו, והדבר היחיד שניתן לעשות הוא לחייך אליו בחזרה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=LKUVZe1wPOI","hiVideo":"https://www.youtube.com/watch?v=-W2dagktUp0"},
"6":{"quoteEn":"One of the unique qualities of a human being is to love even those who have failed.","quoteHi":"मनुष्य की एक विशेषता यह है कि वह उन लोगों से भी प्रेम कर सकता है जो असफल हो गए हैं।","quoteHe":"אחת התכונות המיוחדות של האדם היא לאהוב גם את אלו שנכשלו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=RerzmNafv1s","hiVideo":"https://www.youtube.com/watch?v=l7GR1S-HNGo"},
"7":{"quoteEn":"One of the unique qualities of a human being is to love even those who have failed.","quoteHi":"मनुष्य की एक विशेषता यह है कि वह उन लोगों से भी प्रेम कर सकता है जो असफल हो गए हैं।","quoteHe":"אחת התכונות המיוחדות של האדם היא לאהוב גם את אלו שנכשלו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=dfw60OCIiYs","heLyrics":"https://lyricstranslate.com/en/af-paam-lo-levad-never-alone.html","hiVideo":"https://open.spotify.com/track/6RELGnjAoxtO1IRYUcEcta","hiLyrics":"https://lyricstranslate.com/en/mukesh-ek-pyar-ka-nagma-hai-lyrics.html"},
"8":{"quoteEn":"A person’s worth is measured by the things he devotes himself to.","quoteHi":"मनुष्य का मूल्य उन चीज़ों से मापा जाता है जिनमें वह अपना समय और प्रयास लगाता है।","quoteHe":"ערכו של אדם נמדד לפי הדברים שבהם הוא עוסק.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=73qEBj-yOXA","hiVideo":"https://www.youtube.com/watch?v=9JDSGhhiOwI"},
"9":{"quoteEn":"Life is what our thoughts make it.","quoteHi":"जीवन वैसा ही होता है जैसा हमारी सोच उसे बना देती है।","quoteHe":"החיים הם מה שהמחשבות שלנו גורמות לנו להיות.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Ii8t-XIw6aM","hiVideo":"https://www.youtube.com/watch?v=nOAsaehfPrk"},
"10":{"quoteEn":"Do not waste time arguing about what a good man should be. Be one.","quoteHi":"यह मत बहस करो कि एक अच्छा इंसान क्या होता है। बस वैसा बनो।","quoteHe":"אל נא תתדיין בשאלה מהו אדם טוב, פשוט תהיה כזה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=TwHO5EwBg1U","hiVideo":"https://www.youtube.com/watch?v=lbfWsIpXsCA"},
"31":{"quoteEn":"Good and beautiful people win each other over with kindness.","quoteHi":"अच्छे और सुंदर लोग एक-दूसरे को दयालुता से जीतते हैं।","quoteHe":"אנשים טובים ויפים לכבוש אחד את השני עם חסד.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=sOrr26h6Qnc"},
"63":{"quoteEn":"Even a journey of a thousand miles begins with a single step.","quoteHi":"हज़ार मील की यात्रा भी एक कदम से शुरू होती है।","quoteHe":"גם מסע בן אלף מייל, מתחיל בצעד אחד.","heVideo":"https://www.youtube.com/watch?v=6cGLVj1PUcQ"},
"85":{"quoteEn":"Give a man a fish, and you feed him for a day; teach a man to fish, and you feed him for a lifetime.","quoteHi":"किसी को मछली दो तो उसे एक दिन का खाना; मछली पकड़ना सिखाओ तो जीवन भर का खाना.","quoteHe":"תן לאדם דג - והשבעת אותו ליום אחד, למד את האדם לדוג - והשבעת אותו לכל החיים.","heVideo":"https://www.youtube.com/watch?v=GwzMuMEN2hA"},
"91":{"quoteEn":"It is not because the well is too deep, but because the rope is too short.","quoteHi":"यह इसलिए नहीं कि कुआँ बहुत गहरा है, बल्कि इसलिए कि रस्सी बहुत छोटी है।","quoteHe":"אין זה משום שהבאר עמוקה מדי, אלא בגלל שהחבל קצר.","heVideo":"https://www.youtube.com/watch?v=63pxZIy7m_8","heLyrics":"https://lyricstranslate.com/en/eser-etzbaout-ten-fingers.html","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw","hiLyrics":"https://lyricstranslate.com/en/abhi-mujh-mein-kahin-still-somewhere-inside-me.html"}
});
window.GPC_SONGS_Q1 = window.SONGS_Q1;
