/* songs-q1.js — single Q1 file */
window.SONGS_Q1 = window.SONGS_Q1 || {};
Object.assign(window.SONGS_Q1, {
"1":{
  "quoteEn":"Nature allows every person to cope with their fate.",
  "quoteHi":"प्रकृति हर इंसान को अपने भाग्य का सामना करने की ताकत देती है।",
  "quoteHe":"הטבע מאפשר לכל אדם להתמודד עם גורלו.",
  "heVideo":"https://www.youtube.com/watch?v=zVi8AI9Yl6k",
  "heLyrics":"https://lyricstranslate.com/en/%D7%90%D7%9E%D7%90%D7%9C%D7%94-%D7%95%D7%90%D7%91%D7%90%D7%9C%D7%94-imale-veabale-dear-mommy-dear-papa.html",
  "heLyricsEn":"Dear Mommy, Dear Papa\nRomanians, Tunisians\nYemenites and Moroccans\nIt does not matter what the ethnic group is\nThose who come say thank you\nFrom Poland and from Caucasia\nTonight no one sits still\nAge does not matter at all\nThe main thing is the dance\nNo cash is needed here\nEveryone move your hips\nMillionaire and pauper\nWhat a great night\nDear Mommy, Dear Papa\nHow the place is filling up",
  "heLyricsHe":"אמאל'ה ואבאל'ה\nרומנים טוניסאים\nתימנים ומרוקאים\nלא חשוב מה העדה\nמי שבא נאמר תודה\nמפולין ומקווקז\nהלילה אף אחד לא זז\nלא חשוב בכלל הגיל\nהעיקר זה התרגיל\nלא צריך כאן מזומן\nכולם תזיזו את האגן\nמיליונר וגם תפרן\nאיזה לילה פאנן\nאמאל'ה ואבאל'ה\nאיך המקום מתמלא",
  "hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28",
  "hiLyrics":"https://lyricstranslate.com/en/lag-ja-gale-embrace-me.html",
  "hiLyricsEn":"Embrace me, dear — who knows if this beautiful night will come again\nPerhaps we may never meet again in this life\nFate has given us these few moments\nLook at me up close, as much as you wish\nYour fate may never have this chance again\nCome closer — I will not return again and again\nLet me wrap my arms around you and cry\nMy eyes may never shed such a shower of love again\nEmbrace me, for this beautiful evening may not come again",
  "hiLyricsHi":"लग जा गले कि फिर ये हसीं रात हो न हो\nशायद फिर इस जनम में मुलाकात हो न हो\nहमको मिली हैं आज ये घड़ियाँ नसीब से\nजी भर के देख लीजिये हमको क़रीब से\nफिर आपके नसीब में ये बात हो न हो\nपास आइये कि हम नहीं आएंगे बार-बार\nबाहें गले में डाल के हम रो लें ज़ार-ज़ार\nआँखों से फिर ये प्यार कि बरसात हो न हो\nलग जा गले कि फिर ये हसीं रात हो न हो"
},
"2":{"quoteEn":"The best way to take revenge on an enemy is not to become like him.","quoteHi":"दुश्मन से बदला लेने का सबसे अच्छा तरीका है उस जैसा न बनना।","quoteHe":"הדרך הטובה ביותר להתנקם באויב היא לא להידמות לו.","heVideo":"https://www.youtube.com/watch?v=hySvIlHhCgA","heLyrics":"https://lyricstranslate.com/en/%D7%90%D7%99%D7%9F-%D7%99%D7%95%D7%AA%D7%A8-%D7%9E%D7%95%D7%A2%D7%93%D7%95%D7%A0%D7%99%D7%9D-ein-yoter-moadonim-no-more-clubbing.html","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4","hiLyrics":"https://lyricstranslate.com/en/pal-pal-dil-ke-paas-every-moment-heart.html"},
"16":{"quoteEn":"Optimism, a smile, and hope—how little is needed for us to be happy, and all of it is within us.","quoteHi":"आशावाद, एक मुस्कान और उम्मीद—खुश रहने के लिए कितना कम चाहिए, और यह सब हमारे अंदर ही है।","quoteHe":"אופטימיות, חיוך ותקווה; כמה מעט נחוץ בשביל שנהיה מאושרים, וכל זה נמצא בנו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=LWFEEsU-Y6M","heLyrics":"https://lyricstranslate.com/en/al-tishberi-li-et-alev-dont-break-my-heart.html","hiVideo":"https://www.youtube.com/watch?v=vEe-UgJvUHE","hiLyrics":"https://lyricstranslate.com/en/raabta-raabta.html"},
"17":{"quoteEn":"Observe how the plants, the ants, the birds, the spiders, and the bees all work together to put their part in order in the universe.","quoteHi":"देखो कैसे पौधे, चींटियाँ, पक्षी, मकड़ियाँ और मधुमक्खियाँ मिलकर ब्रह्मांड में अपना-अपना काम व्यवस्थित करती हैं।","quoteHe":"ראה כיצד הצמחים, הנמלים, הציפורים, העכבישים והדבורים – עובדים יחד בכדי לסדר את חלקם ביקום.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=-jfHa5nCOzU","heLyrics":"https://lyricstranslate.com/en/aba-gadol-great-father.html","hiVideo":"https://open.spotify.com/track/6dFQ3W3xuG4ll7cNjIsN2Q","hiLyrics":"https://lyricstranslate.com/en/tujhe-dekha-tujhe-dekha-toh.html"},
"18":{"quoteEn":"All decisions must be calculated.","quoteHi":"सभी निर्णय सोच-समझकर लिए जाने चाहिए।","quoteHe":"כל ההחלטות חייבים להיות מחושבות.","heVideo":"https://www.youtube.com/watch?v=NpAhYc_5-fs","heLyrics":"https://lyricstranslate.com/en/sarit-hadad-avi-shebeshamayim-lyrics.html","hiVideo":"https://open.spotify.com/track/5w0Xpt2YHT2Y3z3e4UUJP7","hiLyrics":"https://lyricstranslate.com/en/kaise-hua-how-did-it-happen.html-0"},
"19":{"quoteEn":"If you want to go fast, go alone. If you want to go far, go together.","quoteHi":"अगर तुम तेज़ जाना चाहते हो तो अकेले जाओ। अगर तुम दूर तक पहुँचना चाहते हो तो साथ चलो।","quoteHe":"אם אתה רוצה ללכת מהר – לך לבד. אם אתה רוצה להגיע רחוק – לך ביחד.","heVideo":"https://www.youtube.com/watch?v=sViXJypEWSk","heLyrics":"https://lyricstranslate.com/en/tikva-hope.html","hiVideo":"https://open.spotify.com/track/4JME3WZOjQi6uQ0YToe4pr","hiLyrics":"https://lyricstranslate.com/en/nanha-munna-rahi-hoon.html-0"},
"20":{"quoteEn":"Perform every act in your life as if it were your last, and you will find peace.","quoteHi":"अगर तुम अपने जीवन का हर काम ऐसे करो जैसे वह आख़िरी हो, तो तुम्हें शांति मिलेगी।","quoteHe":"אם תבצע את כל הפעולות בחייך כאילו הן האחרונות, תמצא מנוחה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Pbz856Zrqn8","heLyrics":"https://lyricstranslate.com/en/ten-li-siman-give-me-sign.html","hiVideo":"https://www.youtube.com/watch?v=_RFUvHlW41A","hiLyrics":"https://lyricstranslate.com/en/khairiyat-importance.html"}
});
Object.keys(window.SONGS_Q1).forEach(function(k){var n=parseInt(k,10);if(!isNaN(n)) window.SONGS_Q1[('000'+n).slice(-3)]=window.SONGS_Q1[k];});
window.GPC_SONGS_Q1 = window.SONGS_Q1;
