/* songs-q1.js — ALL Q1 in this one file. More days get added here, not new files. */
window.SONGS_Q1 = window.SONGS_Q1 || {};
Object.assign(window.SONGS_Q1, {
"1":{"quoteEn":"Nature allows every person to cope with their fate.","quoteHi":"प्रकृति हर इंसान को अपने भाग्य का सामना करने की ताकत देती है।","quoteHe":"הטבע מאפשר לכל אדם להתמודד עם גורלו.","heVideo":"https://www.youtube.com/watch?v=zVi8AI9Yl6k","heLyrics":"https://lyricstranslate.com/en/%D7%90%D7%9E%D7%90%D7%9C%D7%94-%D7%95%D7%90%D7%91%D7%90%D7%9C%D7%94-imale-veabale-dear-mommy-dear-papa.html","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28","hiLyrics":"https://lyricstranslate.com/en/lag-ja-gale-embrace-me.html"},
"2":{"quoteEn":"The best way to take revenge on an enemy is not to become like him.","quoteHi":"दुश्मन से बदला लेने का सबसे अच्छा तरीका है उस जैसा न बनना।","quoteHe":"הדרך הטובה ביותר להתנקם באויב היא לא להידמות לו.","heVideo":"https://www.youtube.com/watch?v=hySvIlHhCgA","heLyrics":"https://lyricstranslate.com/en/%D7%90%D7%99%D7%9F-%D7%99%D7%95%D7%AA%D7%A8-%D7%9E%D7%95%D7%A2%D7%93%D7%95%D7%A0%D7%99%D7%9D-ein-yoter-moadonim-no-more-clubbing.html","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4","hiLyrics":"https://lyricstranslate.com/en/pal-pal-dil-ke-paas-every-moment-heart.html"},
"16":{"quoteEn":"Optimism, a smile, and hope—how little is needed for us to be happy, and all of it is within us.","quoteHi":"आशावाद, एक मुस्कान और उम्मीद—खुश रहने के लिए कितना कम चाहिए, और यह सब हमारे अंदर ही है।","quoteHe":"אופטימיות, חיוך ותקווה; כמה מעט נחוץ בשביל שנהיה מאושרים, וכל זה נמצא בנו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=LWFEEsU-Y6M","hiVideo":"https://www.youtube.com/watch?v=vEe-UgJvUHE"}
});
Object.keys(window.SONGS_Q1).forEach(function(k){var n=parseInt(k,10);if(!isNaN(n)){window.SONGS_Q1[('000'+n).slice(-3)]=window.SONGS_Q1[k];}});
window.GPC_SONGS_Q1=window.SONGS_Q1;
