/* songs-all.js — the one file */
window.SONGS_Q1=window.SONGS_Q1||{};window.GPC_SONGS=window.GPC_SONGS||{};window.SONGS=window.SONGS||{};
Object.assign(window.SONGS_Q1,{
"001":{"quoteEn":"Nature allows every person to cope with their fate.","quoteHi":"प्रकृति हर इंसान को अपने भाग्य का सामना करने की ताकत देती है।","quoteHe":"הטבע מאפשר לכל אדם להתמודד עם גורלו.","heVideo":"https://www.youtube.com/watch?v=zVi8AI9Yl6k","hiVideo":"https://www.youtube.com/watch?v=y2fgw1Oqz28"},
"002":{"quoteEn":"The best way to take revenge on an enemy is not to become like him.","quoteHi":"दुश्मन से बदला लेने का सबसे अच्छा तरीका है उस जैसा न बनना।","quoteHe":"הדרך הטובה ביותר להתנקם באויב היא לא להידמות לו.","heVideo":"https://www.youtube.com/watch?v=hySvIlHhCgA","hiVideo":"https://www.youtube.com/watch?v=AMuRRXCuy-4"},
"010":{"quoteEn":"Do not waste time arguing about what a good man should be. Be one.","quoteHi":"यह मत बहस करो कि एक अच्छा इंसान क्या होता है। बस वैसा बनो।","quoteHe":"אל נא תתדיין בשאלה מהו אדם טוב, פשוט תהיה כזה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=TwHO5EwBg1U","hiVideo":"https://www.youtube.com/watch?v=lbfWsIpXsCA"},
"015":{"quoteEn":"Despite a broken heart, people keep going.","quoteHi":"टूटे हुए दिल के बावजूद, लोग आगे बढ़ते रहते हैं।","quoteHe":"למרות הלב השבור, אנשים ממשיכים הלאה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=5kz28Hh9VVk","hiVideo":"https://www.youtube.com/watch?v=xRb8hxwN5zc"},
"020":{"quoteEn":"Perform every act in your life as if it were your last, and you will find peace.","quoteHi":"हर काम आख़िरी की तरह करो, शांति मिलेगी।","quoteHe":"עשה כל מעשה כאילו היא האחרונה ותמצא מנוחה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Pbz856Zrqn8"},
"021":{"quoteEn":"At any hour you choose, it is within your power to withdraw into yourself.","quoteHi":"जब भी तुम चाहो, एकांत में जा सकते हो।","quoteHe":"כל שעה שתחפוץ, בידך להתבודד.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=cLPFb305l44"},
"030":{"quoteEn":"Hunger is the best sauce.","quoteHi":"सबसे अच्छा स्वाद भूख देती है।","quoteHe":"הרוטב הטוב ביותר הוא רעב.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=VfD7WNKNrAQ"},
"051":{"quoteEn":"Wise men speak because they have something to say; fools because they have to say something.","quoteHi":"बुद्धिमान इसलिए बोलते हैं कि उनके पास कहने को कुछ है.","quoteHe":"חכמים מדברים כי יש להם מה לומר.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=HXz70eAaiMA"},
"091":{"quoteEn":"It is not because the well is too deep, but because the rope is too short.","quoteHi":"यह इसलिए नहीं कि कुआँ बहुत गहरा है, बल्कि इसलिए कि रस्सी बहुत छोटी है।","quoteHe":"אין זה משום שהבאר עמוקה מדי, אלא בגלל שהחבל קצר.","heVideo":"https://www.youtube.com/watch?v=63pxZIy7m_8","hiVideo":"https://www.youtube.com/watch?v=oWKgpB2zpgw"}
});
(function(){var s=window.SONGS_Q1;Object.keys(s).forEach(function(k){var n=parseInt(k,10);if(isNaN(n))return;s[('000'+n).slice(-3)]=s[k];s[String(n)]=s[k];window.GPC_SONGS[('000'+n).slice(-3)]=s[k];window.SONGS[('000'+n).slice(-3)]=s[k];});function p(){if(window.GPCPaintSongs)GPCPaintSongs();}p();setTimeout(p,400);setTimeout(p,1500);})();
