/* songs-q1d.js days 016-030 */
window.SONGS_Q1 = window.SONGS_Q1 || {};
Object.assign(window.SONGS_Q1, {
"16":{"quoteEn":"Optimism, a smile, and hope—how little is needed for us to be happy, and all of it is within us.","quoteHi":"आशावाद, एक मुस्कान और उम्मीद—खुश रहने के लिए कितना कम चाहिए, और यह सब हमारे अंदर ही है।","quoteHe":"אופטימיות, חיוך ותקווה; כמה מעט נחוץ בשביל שנהיה מאושרים, וכל זה נמצא בנו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=LWFEEsU-Y6M","heLyrics":"https://lyricstranslate.com/en/al-tishberi-li-et-alev-dont-break-my-heart.html","hiVideo":"https://www.youtube.com/watch?v=vEe-UgJvUHE","hiLyrics":"https://lyricstranslate.com/en/raabta-raabta.html"},
"17":{"quoteEn":"Observe how the plants, the ants, the birds, the spiders, and the bees all work together to put their part in order in the universe.","quoteHi":"देखो कैसे पौधे, चींटियाँ, पक्षी, मकड़ियाँ और मधुमक्खियाँ मिलकर ब्रह्मांड में अपना-अपना काम व्यवस्थित करती हैं।","quoteHe":"ראה כיצד הצמחים, הנמלים, הציפורים, העכבישים והדבורים – עובדים יחד בכדי לסדר את חלקם ביקום.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=-jfHa5nCOzU","heLyrics":"https://lyricstranslate.com/en/aba-gadol-great-father.html","hiVideo":"https://open.spotify.com/track/6dFQ3W3xuG4ll7cNjIsN2Q","hiLyrics":"https://lyricstranslate.com/en/tujhe-dekha-tujhe-dekha-toh.html"},
"18":{"quoteEn":"All decisions must be calculated.","quoteHi":"सभी निर्णय सोच-समझकर लिए जाने चाहिए।","quoteHe":"כל ההחלטות חייבים להיות מחושבות.","heVideo":"https://www.youtube.com/watch?v=NpAhYc_5-fs","heLyrics":"https://lyricstranslate.com/en/sarit-hadad-avi-shebeshamayim-lyrics.html","hiVideo":"https://open.spotify.com/track/5w0Xpt2YHT2Y3z3e4UUJP7","hiLyrics":"https://lyricstranslate.com/en/kaise-hua-how-did-it-happen.html-0"},
"19":{"quoteEn":"If you want to go fast, go alone. If you want to go far, go together.","quoteHi":"अगर तुम तेज़ जाना चाहते हो तो अकेले जाओ। अगर तुम दूर तक पहुँचना चाहते हो तो साथ चलो।","quoteHe":"אם אתה רוצה ללכת מהר – לך לבד. אם אתה רוצה להגיע רחוק – לך ביחד.","heVideo":"https://www.youtube.com/watch?v=sViXJypEWSk","heLyrics":"https://lyricstranslate.com/en/tikva-hope.html","hiVideo":"https://open.spotify.com/track/4JME3WZOjQi6uQ0YToe4pr","hiLyrics":"https://lyricstranslate.com/en/nanha-munna-rahi-hoon.html-0"},
"20":{"quoteEn":"Perform every act in your life as if it were your last, and you will find peace.","quoteHi":"अगर तुम अपने जीवन का हर काम ऐसे करो जैसे वह आख़िरी हो, तो तुम्हें शांति मिलेगी।","quoteHe":"אם תבצע את כל הפעולות בחייך כאילו הן האחרונות, תמצא מנוחה.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Pbz856Zrqn8","heLyrics":"https://lyricstranslate.com/en/ten-li-siman-give-me-sign.html","hiVideo":"https://www.youtube.com/watch?v=_RFUvHlW41A","hiLyrics":"https://lyricstranslate.com/en/khairiyat-importance.html"},
"21":{"quoteEn":"At any hour you choose, it is within your power to withdraw into yourself.","quoteHi":"जब भी तुम चाहो, तुम्हारे हाथ में है कि तुम एकांत में जा सको।","quoteHe":"כל שעה שתחפוץ, בידך להתבודד.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=cLPFb305l44","heLyrics":"https://lyricstranslate.com/en/boom-boom.html-23","hiVideo":"https://www.youtube.com/watch?v=cYOB941gyXI","hiLyrics":"https://lyricstranslate.com/en/arijit-singh-hawayein-english"},
"22":{"quoteEn":"We are all fleeting—the one who remembers and the one who is remembered.","quoteHi":"हम सब नश्वर हैं—याद करने वाला भी और जिसे याद किया जाता है वह भी।","quoteHe":"כולנו בני חלוף – הזוכר, ומושא זכרונו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=VT1R37o-d3I","heLyrics":"https://lyricstranslate.com/en/kakh-nolad-hatseva-thus-color-was-born.html","hiVideo":"https://www.youtube.com/watch?v=M1mVWZKFcUw","hiLyrics":"https://lyricstranslate.com/en/hindi-children-songs-nanha-munna-rahi-hoon-lyrics.html"},
"23":{"quoteEn":"Nowhere can a person find a more peaceful refuge than in his own soul.","quoteHi":"कहीं भी मनुष्य को अपनी आत्मा से अधिक शांत आश्रय नहीं मिल सकता।","quoteHe":"בשום מקום לא יוכל האדם למצוא מקלט שליו יותר מאשר בנפשו.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=u95eSORTRDs","heLyrics":"https://lyricstranslate.com/en/im-confused.html","hiVideo":"https://www.youtube.com/watch?v=Umqb9KENgmk","hiLyrics":"https://lyricstranslate.com/en/tum-hi-ho-you-are.html"},
"24":{"quoteEn":"Whenever trouble comes to you, remember: to bear it with nobility is the wealth of the soul.","quoteHi":"जब भी तुम्हारे उपर कोई मुसीबत आए, याद रखो—उसे गरिमा के साथ सहना ही आत्मा की संपत्ति है।","quoteHe":"בכל צרה שתבוא עליך זכור; לשאת אותה באצילות, הוא עושרה של הנפש.","cite":"Marcus Aurelius","heVideo":"https://www.youtube.com/watch?v=Hl0VJo0LZao","heLyrics":"https://lyricstranslate.com/en/oevet-tachim-i-love-life.html","hiVideo":"https://www.youtube.com/watch?v=UNs50T6EYwE","hiLyrics":"https://lyricstranslate.com/en/sun-saathiya-listen-o-friend.html"},
"25":{"quoteEn":"If you find a good wife, you will be happy; if not, you will become a philosopher.","quoteHi":"अगर तुम्हें अच्छी पत्नी मिल जाए तो तुम खुश रहोगे; अगर नहीं, तो तुम दार्शनिक बन जाओगे।","quoteHe":"אם אתה מוצא אישה טובה אתה תהיה מאושר, אם לא, אתה תהיה פילוסוף.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=ty0Q9g7gClU","heLyrics":"https://lyricstranslate.com/en/uncle-america.html","hiVideo":"https://open.spotify.com/track/3t3wsY5IdLVzB9WidegJSU","hiLyrics":"https://lyricstranslate.com/en/atif-aslam-jeene-laga-hoon-english"},
"26":{"quoteEn":"Do not let grass grow on the path of friendship.\nTrue friendship must be cultivated often.","quoteHi":"दोस्ती के रास्ते पर घास मत उगने दो।\nसच्ची दोस्ती को बार-बार संभालना और बढ़ाना पड़ता है।","quoteHe":"אל תתנו לדשא לצמוח על נתיב הידידות.\nידידות אמיתית חייבת להיות מטופחת לעתים קרובות.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=oLAOEVYDcps","heLyrics":"https://lyricstranslate.com/en/mi-hayom-biladai-who-are-you-today-without-me.html","hiVideo":"https://open.spotify.com/track/5YyXp1D6QxK2yZtXOtOid5","hiLyrics":"https://lyricstranslate.com/en/posham-pa-posham-pa.html"},
"27":{"quoteEn":"Kings or rulers are not those who hold the scepter, but those who know how to command.\nAuthority arises from power, not the other way around.","quoteHi":"राजा या शासक वे नहीं होते जिनके पास राजदंड होता है, बल्कि वे होते हैं जो आदेश देना जानते हैं।","quoteHe":"מלכים או שליטים אינם אלה שיש להם שרביט, אלא אלה שיודעים איך לפקד.\nהרשות נובעת מן הכוח, ולא להיפך.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=w56GvpfcP6c","heLyrics":"https://lyricstranslate.com/en/lo-rotze-lehiout-atzov-i-dont-want-be-sad.html","hiVideo":"https://open.spotify.com/track/4brSaQIT3bnnE41D042fgL","hiLyrics":"https://lyricstranslate.com/en/tu-hai-ki-nahi-are-you-there-or-not.html"},
"28":{"quoteEn":"No one is happy throughout their entire life.\nWe all have ups and downs; it’s quite normal.","quoteHi":"कोई भी अपने पूरे जीवन में हमेशा खुश नहीं रहता।\nहम सभी के जीवन में उतार-चढ़ाव आते हैं; यह बिल्कुल सामान्य है।","quoteHe":"אף אחד לא מאושר לאורך כל חייהם.\nלכולנו יש עליות ומורדות, זה די רגיל.","cite":"Euripides","heVideo":"https://www.youtube.com/watch?v=nbW_Hf-wfrc","heLyrics":"https://lyricstranslate.com/en/tirkod-lenetzach-dance-forever.html","hiVideo":"https://open.spotify.com/track/6eO9LvEiMqh1CAsa6y3wXP","hiLyrics":"https://lyricstranslate.com/en/bol-do-na-zara-just-say-it.html"},
"29":{"quoteEn":"Human science consists more in the destruction of errors than in the discovery of truth.","quoteHi":"मानव ज्ञान सत्य की खोज से अधिक गलतियों को नष्ट करने में लगा होता है।","quoteHe":"המדע האנושי מורכב יותר בהרס שגיאות מאשר גילוי האמת.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=QtfyyuZrUqY","heLyrics":"https://lyricstranslate.com/en/numi-numi-sleep-sleep.html","hiVideo":"https://open.spotify.com/track/0Bz7dfqPY4JOGZO3O1j8Wh","hiLyrics":"https://lyricstranslate.com/en/bulleya-bulleya.html"},
"30":{"quoteEn":"Hunger is the best sauce.","quoteHi":"सबसे अच्छा स्वाद भूख देती है।","quoteHe":"הרוטב הטוב ביותר הוא רעב.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=VfD7WNKNrAQ","heLyrics":"https://lyricstranslate.com/en/etzli-hakol-beseder-everythings-fine-me.html","hiVideo":"https://open.spotify.com/track/3TAhWtQnpoL5Vl9VQPl9fU","hiLyrics":"https://lyricstranslate.com/en/senorita-lyrics.html"}
});
window.GPC_SONGS_Q1 = window.SONGS_Q1;
