/* songs-q1e.js 032-040 */
window.SONGS_Q1 = window.SONGS_Q1 || {};
Object.assign(window.SONGS_Q1, {
"32":{"quoteEn":"The only true knowledge is the knowledge that comes from within.","quoteHi":"सच्चा ज्ञान वही है जो भीतर से आता है।","quoteHe":"רק הידע שמגיע מבפנים הוא ידע אמיתי.","cite":"Socrates","heVideo":"https://www.youtube.com/watch?v=RMwhKx8_X8A","heLyrics":"https://lyricstranslate.com/en/medabrim-talking.html","hiVideo":"https://open.spotify.com/track/3OAFzjwWionh8OfM4kgf2R","hiLyrics":"https://lyricstranslate.com/en/main-yahaa-hoon-i-am-here.html"},
"33":{"quoteEn":"Happiness is in freedom, and freedom is in courage.","quoteHi":"खुशी स्वतंत्रता में है, और स्वतंत्रता साहस में है।","quoteHe":"האושר הוא בחופש, וחופש באומץ.","cite":"Pericles","heVideo":"https://www.youtube.com/watch?v=MQuaIYRDO6s","heLyrics":"https://lyricstranslate.com/en/klum-nothing.html-2","hiVideo":"https://open.spotify.com/track/0rUN8ascPVT9iiLzC5ocPw"},
"34":{"quoteEn":"Music is to the soul what exercise is to the body.","quoteHi":"संगीत आत्मा के लिए वही है जो व्यायाम शरीर के लिए है।","quoteHe":"מוסיקה היא לנשמה איזו התעמלות היא לגוף.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=fZ26yiGviZA","heLyrics":"https://lyricstranslate.com/en/leyad-hayam-sea.html","hiVideo":"https://open.spotify.com/track/1AlatlIkROgLvG6pgBBnAz","hiLyrics":"https://lyricstranslate.com/en/kishore-kumar-roop-tera-mastana-english"},
"35":{"quoteEn":"The human body is the chariot; the self is the one who drives it; thought is the reins, and the feelings are the horses.","quoteHi":"मानव शरीर रथ है; आत्मा उसका सारथी है; विचार उसकी लगाम हैं और भावनाएँ उसके घोड़े हैं।","quoteHe":"גוף האדם הוא המרכבה; העצמי, האיש שמוביל אותו; המחשבה היא המושכות, והרגשות הם הסוסים.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=CMW0zhhV0yI","heLyrics":"https://lyricstranslate.com/en/baleilot-night.html","hiVideo":"https://open.spotify.com/track/12DVyDf5uqrcRr3BmqDF2w","hiLyrics":"https://lyricstranslate.com/en/chingari-koi-bhadke-when-spark-ignites.html"},
"36":{"quoteEn":"There is no man so cowardly that love does not make him brave and turn him into a hero.","quoteHi":"कोई भी मनुष्य इतना कायर नहीं होता कि प्रेम उसे साहसी बनाकर नायक न बना दे।","quoteHe":"אין אדם כה פחדן שאהבה לא עושה אמיץ ולהפוך לגיבור.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=YhqB-N3A19k","heLyrics":"https://lyricstranslate.com/en/ohev-liyot-babayit-live-be-home.html","hiVideo":"https://open.spotify.com/track/0eNiqkazTEYJJ8fMRPyJx8","hiLyrics":"https://lyricstranslate.com/en/laila-main-laila-laila-i-am-laila.html"},
"37":{"quoteEn":"Listen, and you will be wise. The beginning of wisdom is silence.","quoteHi":"सुनो, और तुम बुद्धिमान बनोगे। बुद्धि की शुरुआत मौन से होती है।","quoteHe":"תשמע, אתה תהיה חכם. תחילת החוכמה היא שתיקה.","cite":"Pythagoras","heVideo":"https://www.youtube.com/watch?v=PbHmqjolaa4","heLyrics":"https://lyricstranslate.com/en/chasera-li-i-miss-you.html","hiVideo":"https://www.youtube.com/watch?v=PbHmqjolaa4"},
"38":{"quoteEn":"Poverty does not come from the reduction of wealth, but from the multiplication of desires.","quoteHi":"गरीबी धन के कम होने से नहीं आती, बल्कि इच्छाओं के बढ़ने से आती है।","quoteHe":"העוני אינו בא על ידי הפחתת העושר, אלא על ידי הכפל של הרצונות.","cite":"Plato","heVideo":"https://www.youtube.com/watch?v=TxxmM-zEWP0","heLyrics":"https://lyricstranslate.com/en/qomando-mohi-mind-commando.html","hiVideo":"https://open.spotify.com/track/06WBL2qDIabVl2Q1gpNvOa","hiLyrics":"https://lyricstranslate.com/en/mohommad-rafi-bahaaron-phool-barsaao-lyrics.html"},
"39":{"quoteEn":"Tyrants surround themselves with bad men because they love to be flattered, and no man of high spirit will flatter them.","quoteHi":"तानाशाह अपने चारों ओर बुरे लोगों को रखते हैं, क्योंकि उन्हें चापलूसी पसंद होती है, और ऊँचे चरित्र वाला व्यक्ति उनकी चापलूसी नहीं करेगा।","quoteHe":"הטירנים מקיפים את עצמם באנשים רעים כי הם אוהבים להיות מוחמא ולא איש של רוח גבוהה יחמיא להם.","cite":"Aristotle","heVideo":"https://www.youtube.com/watch?v=ooSJ7TD0MKs","heLyrics":"https://lyricstranslate.com/en/aba-father.html","hiVideo":"https://open.spotify.com/track/2GuUy6p5p7068dEKeNPIyd","hiLyrics":"https://lyricstranslate.com/en/sachin-jigar-param-sundari-lyrics"},
"40":{"quoteEn":"The aim of art is to represent not the outward appearance of things, but their inner significance.","quoteHi":"कला का उद्देश्य वस्तुओं की बाहरी रूपरेखा की नकल करना नहीं, बल्कि उनके भीतर के सार को प्रकट करना है।","quoteHe":"מטרת האמנות היא לתת לגוף את מהותו הסודית של הדברים, לא להעתיק את הופעתם.","cite":"Aristotle","heVideo":"https://www.youtube.com/watch?v=oQbh5Kvet04","heLyrics":"https://lyricstranslate.com/en/million-dollar-million-bucks.html","hiVideo":"https://open.spotify.com/track/2rOnSn2piaqLAlYjtfUBlY","hiLyrics":"https://lyricstranslate.com/en/jubin-nautiyal-raataan-lmbiyaan-lmbiyaan-re-raataan-lamb-lyrics.html"}
});
window.GPC_SONGS_Q1 = window.SONGS_Q1;
